// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRoFPeU-cC-nrUwM_HEna7JdK-3XBz8lE',
    appId: '1:1068389368008:web:b6e77ce1f83f22f9ade5fd',
    messagingSenderId: '1068389368008',
    projectId: 'learning-fb-1314',
    authDomain: 'learning-fb-1314.firebaseapp.com',
    storageBucket: 'learning-fb-1314.firebasestorage.app',
    measurementId: 'G-K5FT7M3LWS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBamUm1m_a-JUDWbxVF1q5wrfdHbzZVNgM',
    appId: '1:1068389368008:android:db08116b7debdf71ade5fd',
    messagingSenderId: '1068389368008',
    projectId: 'learning-fb-1314',
    storageBucket: 'learning-fb-1314.firebasestorage.app',
  );
}
